# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cda847cc4c6b3a370649f5f0fab9b1234e55ef7b5e51c5a90bf4e71a58e0e3b4b3c7896caafc4d04fb46bcc2afa1e419ecc45a98a2c525da867e970e1359438

test:
  secret_key_base: 9595fd60f072dd919b4856a0c3f844b816422d2dc00f8973ce280f08dfe7a49b05eac754d9e0bf1ff77205099e29404add9b178ff73e389758f112cc4c4e41d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
